### ISSUE TITLE
Suggested improvements to Mute & Settings buttons

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#10]
Bug:
Mute button not visible during settlement phase.

UI improvement:
Move mute option into settings menu so the preference gets saved between sessions.
Move Settings button to bottom right corner and have it always available. (The settings will get more complex overtime, might want to make it easily accessible from the start.)

Bonus: Separately mute background music and narration?

**Comment by prikhodkop** [comment]
Done.
