### ISSUE TITLE
Hunt event selector does not allow event no. "100"

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#12]
Instead you have to type "00" which isn't very intuitive for some people.

**Comment by prikhodkop** [comment]
Now with On screen keypad instead of '0' lantern icon is shown

**Comment by prikhodkop** [comment]
<img width="665" alt="Screenshot 2019-05-29 at 09 46 55" src="https://user-images.githubusercontent.com/7735127/58535493-d2cb7d80-81f6-11e9-8807-26295dc7b0bf.png">

**Comment by jparkerweb** [comment]
good call... maybe an entry of "00" could trigger the 100 event.  This would mimic dice rolls as well.  Will look into it.

**Comment by prikhodkop** [comment]
Yes, that's how it works now: 00 triggers 100. However, @Creepo90 pointed that it may not be non intuitive especially with keyboard input.

**Comment by prikhodkop** [comment]
I suppose, the best solution (in addition to adding the lantern icon to key pad, which I already did), would be printing lantern instead of '0' in the input. However, I don't know how to do it yet :/
