### ISSUE TITLE
Fix hunt event typos!

### ISSUE THREAD

**Issue by prikhodkop** [prikhodkop/kdm_story_app#17]
Hunt 22 has a typo "Does settlemnt has", and no response when 1-5 is rolled

But there could be many more - need to check all

**Comment by Creepo90** [comment]
I'm currently working on  proofreading them, but I'm only up to 12.
The simple ones I've been fixing in my fork and if I run into things that require bit more coding I'll document and forward to you after I'm done with the others.  For now it's probably best if only I focus on them to not do the same corrections twice.

**Comment by prikhodkop** [comment]
Great!

**Comment by prikhodkop** [comment]
merged to master
