### ISSUE TITLE
A confirmation prompt when esc is pressed

### ISSUE THREAD

**Issue by prikhodkop** [prikhodkop/kdm_story_app#18]
Need to add confirmation prompt before app is closed

**Comment by Creepo90** [comment]
I was also thinking it was a bit abrupt way to close it.
One idea that I got was that Esc could first switch it to windowed mode and a subsequent Esc would close it (possibly with a prompt). I've used some programs that behave this way and I felt it to be quite intuitive. (I know I can just press F11 but I know some people are bad with hotkeys.)

**Comment by prikhodkop** [comment]
Why don't just show pop up window, asking you to confirm quit? (+later we may add settings to it)

**Comment by Creepo90** [comment]
Yeah I wasn't saying it doesn't need a prompt as it is, it will definitely benefit from one.
Just wanted to throw the idea out there.

**Comment by prikhodkop** [comment]
Done.
