### ISSUE TITLE
Hunt event 6 modification for clarity

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#19]
I think this one needs an additional check to make it more clear, so the flow would roughly be:

Check - Sculpture
Yes - Stuff happens. -> Next question.
No - Blank. -> Next question.

Check - Are all survivors insane?
Yes - Survivors continue their hunt. -> End this event.
No - Survivors may rest here longer. -> Next question.

Choice - Do you want to rest longer?
Yes - Stuff happens. -> End this event.
No - Survivors continue their hunt. -> End this event.

Let me know when you've updated it and I'll copy it to my version that's under proofreading.

**Comment by prikhodkop** [comment]
@Creepo90 Fixed that.
