### ISSUE TITLE
Intro improvements

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#21]
Rename Intro (menu) to Prologue.
Rename Intro (video) to Prologue.
Add First Story: White Lion showdown setup instructions from pg.26 (crucial info noted in the picture).
![Prologue SD](https://user-images.githubusercontent.com/51092659/58801807-42d16d80-8614-11e9-910b-20a6fa39f64d.jpg)

Layout on the menu:
Prologue-video
First Story: White Lion -showdown

Prologue-video should take you straight to showdown setup after video ends.

**Comment by prikhodkop** [comment]
@Creepo90 Added first story event that starts after the intro video: https://youtu.be/4FrahSDaLZE
