### ISSUE TITLE
Develop-menu UI-improvements

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#31]
General:
Add an instructional text to develop-menu that tells you to double click on locations/innovations to make them persistent and affect the actions-tab. I only found this AFTER our session with pure accident.

Innovations:
Option 1: Significantly speed up animation so card pops up as soon as mouse hovers over innovation name and make single click do nothing.
or
Option 2: Make single click show and unshow innovation (just like locations).

**Comment by prikhodkop** [comment]
Addressed this at 3.1 as well
