### ISSUE TITLE
Starvation tweak

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#35]
"Survivors must spend 1d5 basic resources!" can be misleading. To make it more clear and inline with rulebook it should isntead say exactly as it says on the hunt board:

"Remove d5 resources from settlement storage."
OR (for added flavor as per the rulebook)
"The hunting team takes too long to bring food back home.
Remove d5 resources from settlement storage."

ALSO, make the starvation pop-up stay visible until you click it away. In actual game play it can take a moment to apply starvation effects into the settlement sheet.

**Comment by prikhodkop** [comment]
Fixed
