### ISSUE TITLE
Drawn settlement event not showing up

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#37]
Started new settlement phase.
Drew random settlement event.
This happens (some sort of error displaying an image?).
Happens sometimes, not always.
![20200112_152458](https://user-images.githubusercontent.com/51092659/72909648-076ce600-3d40-11ea-8bfe-19355359b4f8.jpg)

**Comment by prikhodkop** [comment]
Fixed in master! (It happened when one started new year -> opened other story event before drawing other settlement event and then returned back to settlement screen)
