### ISSUE TITLE
Back button position too low with large scaling in windows

### ISSUE THREAD

**Issue by prikhodkop** [prikhodkop/kdm_story_app#5]
<img width="1276" alt="Screenshot 2019-05-24 at 01 07 53" src="https://user-images.githubusercontent.com/7735127/58289929-9ba53880-7dc0-11e9-8b0f-0bc4841c879f.png">

Back button text is cut in the bottom.

**Comment by jparkerweb** [comment]
at what resolution does this start becoming an issue?

**Comment by prikhodkop** [comment]
fixed
