### ISSUE TITLE
Suggestion: Add Oxidized gear to Exhausted Lantern Hoard Location

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#51]
Just thought it'd be handy to have the Oxidized Lantern gear displayed in the Exhausted Lantern Hoard settlement location as it currently only holds the Survivors Lantern.

**Comment by Creepo90** [comment]
And while you do this, also add the Survivor Lantern back as it's missing from 3.1.

**Comment by prikhodkop** [comment]
Added. Thanks for suggestion!
