### ISSUE TITLE
Music comes back on when returning from story event to hunt board

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#61]
To replicate:
Have music set "off" in options.
Select any hunt.
Open a story event, for example Overwhelming Darkness.
Return to hunt via lower left corner arrow.
Music plays even though it's "off" in settings.

Music stops again if you go to settlement or another story event but if you return back to hunt from story event it starts again.

**Comment by prikhodkop** [comment]
Fixed!
