### ISSUE TITLE
Glossary bug

### ISSUE THREAD

**Issue by SirYaro** [prikhodkop/kdm_story_app#69]
Steps to replicate:
- go to http://web.kdm-story.site/#!/settlement
- click question mark
- type and choose any term ("miecz" in my case)
- click question mark to close index
- click question mark to open index

Result: Found term (or terms) are still there and can't be closed now (unless u refresh the webpage)

![obraz](https://user-images.githubusercontent.com/5879723/89810638-aa9b1680-db3d-11ea-96ff-3b71b732301d.png)

**Comment by prikhodkop** [comment]
Fixed. Thanks for reporting!
