### ISSUE TITLE
wrong antelope assignment

### ISSUE THREAD

**Issue by SirYaro** [prikhodkop/kdm_story_app#70]
Rules:
![obraz](https://user-images.githubusercontent.com/5879723/90232395-e9222100-de1c-11ea-8f0f-31fe7dd4406c.png)

kdm-story hunt phase at it's start
![obraz](https://user-images.githubusercontent.com/5879723/90232535-1f5fa080-de1d-11ea-8542-b53b14a7c325.png)

**Comment by prikhodkop** [comment]
Fixed. Thanks for reporting!
