### ISSUE TITLE
Some "popup" options are missing from the web app.

### ISSUE THREAD

**Issue by bojangles787** [prikhodkop/kdm_story_app#77]
Some selection options are missing from the web application that make the flow less convenient.  These options do exist in the desktop application.

Example of missing selection options:

- "After victory..." popup at the bottom of the First Story.
- "To Settlement" popup at the bottom of the Returning Survivors
- Severe Injury and Brain Trauma charts
- Popup information for Principles

I've tried this with Chrome, Edge, and Safari and the issue is the same.  I've tried turning off pop-up blockers and the issue is the same.

**Comment by prikhodkop** [comment]
This was the bug. Should be fixed in the current web version.
