### ISSUE TITLE
Game Over Milestones

### ISSUE THREAD

**Issue by dilich84** [prikhodkop/kdm_story_app#80]
Hi, the milestones for lost settlements trigger different than described (after 1,2,3 and 4 lost settlements) . Correct was: first milestone after 5 lost settlements, second after 10, etc.. 

Best Regards,

Joerg

**Comment by prikhodkop** [comment]
![game over](https://user-images.githubusercontent.com/7735127/104634646-eff5de00-56b1-11eb-9d7f-514b11091c30.png)
Are you sure? The story event says you should pick it after every successive settlement lost.

**Comment by dilich84** [comment]
The event says you should fill in a box and continue to earn milestone bonuses...On the campaign sheet you must fill 5 boxes to trigger the milestone (see picture)Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Pavel Prikhodko <notifications@github.com> Datum: 14.01.21  19:47  (GMT+01:00) An: prikhodkop/kdm_story_app <kdm_story_app@noreply.github.com> Cc: dilich84 <joerg.schaller@hotmail.de>, Author <author@noreply.github.com> Betreff: Re: [prikhodkop/kdm_story_app] Game Over Milestones (#80) 

Are you sure? The story event says you should pick it after every successive settlement lost.

**Comment by dilich84** [comment]
![20210114_200448](https://user-images.githubusercontent.com/77172896/104648072-ede04f00-56b2-11eb-8b90-1565043f231b.jpg)

**Comment by prikhodkop** [comment]
Yes, you are right! Thanks for correcting me) Fixed in the web version.

**Comment by dilich84** [comment]
[cid:97f7c2ec-64c3-405e-96d5-d1c9861f2e29]<https://www.transfernow.net/dl/confirmation>
