### ISSUE TITLE
Random SE draw button disappears

### ISSUE THREAD

**Issue by Creepo90** [prikhodkop/kdm_story_app#9]
Bug:
Opened Settlement
Drew random settlement event (SE)
Opened a story event
Came back to Settlement
SE draw button has disappeared

Further improvement:
Make the drawn SE persistent so it stays, even if you open a story event in between.
Why it'd be useful?
For example you could resolve SE, resolve story event, come back to SE to use it's lingering effects.

**Comment by prikhodkop** [comment]
Fixed disappearing buttons: https://github.com/prikhodkop/kdm_story_app/commit/0f47bcaebd1b6f9827b16f3ac04a58d425e8095a

Persistancy is yet to come :)

**Comment by prikhodkop** [comment]
Made SE draw result persistent
